<?php

namespace Devin345458\Api\Controller;

use App\Controller\AppController as BaseController;

class AppController extends BaseController
{
    public function beforeRender(EventInterface $event)
    {
        parent::beforeRender($event); // TODO: Change the autogenerated stub
        $this->_viewBuilder->setHelpers(['Api.Swagger'], true);
    }
}
